Project/final-pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

Project/final-pjt/finalpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/final-pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/genre/', views.category_genre, name='category_genre'),
    path('category/genre/<str:genre_name>/', views.category_genre_detail, name='category_genre_detail'),
    path('movie/<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('category/era/', views.category_era, name='category_era'),
    path('category/era/<str:era>/', views.category_era_detail, name='category_era_detail'),
    path('category/country/', views.category_country, name='category_country'),
    path('category/country/<str:country>/', views.category_country_detail, name='category_country_detail'),
    path('movie/<int:movie_pk>/click/', views.movie_click, name='movie_click'),
    path('movie/recommend/', views.movie_recommend, name='movie_recommend'),
]

Project/final-pjt/templates/_nav.html
{% load static %}
{% load bootstrap5 %}

  <div class="my-nav">
    <div class="my-logo">
      <a href="{% url 'movies:index' %}"><img src="{% static 'images/logo_new_5.png'%}" alt="logo" style="width: 35%"></a>
    </div>
    
    <div class="my-info">
      {% if request.user.is_authenticated %}
        <a href="{% url 'movies:movie_recommend' %}">
          <img src="{% static 'images/recommend_new_3.png'%}" alt="recommend" class="me-2">
        </a>
        <a href="{% url 'accounts:profile' user.username %}" class="m-4 text-decoration-none">
          <img src="{% static 'images/profile_new_3.png'%}" alt="profile">
        </a>

        <form action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="mt-2" style="border: 0px; background-color: transparent;"><img src="{% static 'images/logout_new_3.png'%}" alt="logout logo"></button>
        </form>
        {% comment %} 
          <div class="m-2">
            <form action="{% url 'accounts:delete' %}" method="POST"> 
              {% csrf_token %}
              <input type="submit" class="btn btn-danger" value="회원탈퇴">
            </form>
          </div>
          <a href="{% url 'accounts:update' %}" class="ms-2 btn btn-warning">회원정보수정</a> 
        {% endcomment %}
      {% else %}
        <a href="{% url 'accounts:login' %}" class="m-4 text-decoration-none">
          <img src="{% static 'images/login_new_3.png'%}" alt="login logo">
        </a>
        <a href="{% url 'accounts:signup' %}">
          <img src="{% static 'images/signup_new_3.png'%}" alt="signup logo">
        </a>
      {% endif %}
    </div>
  </div>

Project/final-pjt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🌲 Merry Christmas 🎅</title>    
    {% comment %} bootstrap5 cdn 추가 {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> 
    {% comment %} AnyChart cdn {% endcomment %}
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-base.min.js" type="text/javascript"></script>
    {% comment %} <link rel="stylesheet" href="{% static "style/background.css" %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static "style/_nav.css" %}">
    <link rel="stylesheet" href="{% static "style/category.css" %}">
    <link rel="stylesheet" href="{% static "style/login_signup.css" %}">
    <link rel="stylesheet" href="{% static "style/profile.css" %}">
    <link rel="stylesheet" href="{% static "style/snow.css" %}">

  </head>
  <body>
    {% include '_nav.html' %}
      {% comment %} <div class="my-back"><a href="javascript:history.back()" class="btn recommend-btn btn-dark">back</a></div> {% endcomment %}
      {% comment %} 자바스크립트의 History Object 사용하여 웹 브라우저 상 사용자가 방문한 URL 정보를 활용할 수 있다 {% endcomment %}

    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    <div class="snowflake"></div>
    
    {% block content %}
    {% endblock content %}

    {% comment %} bootstrap5 cdn 추가 {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% comment %} AnyChart cdn {% endcomment %}
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-bundle.min.js"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>