Project/PJT08/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

Project/PJT08/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comments/<int:comment_pk>/like/', views.like_comment, name='like_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/recomments/create/', views.create_recomment, name='create_recomment'),
    path('<int:review_pk>/comments/<int:comment_pk>/recomments/<int:recomment_pk>/like/', views.like_recomment, name='like_recomment'),
]

Project/PJT08/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

Project/PJT08/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

Project/PJT08/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <nav>
        {% if user.is_authenticated %}
        <h3>Hello, {{ user.username }}</h3>
        <a href="{% url 'accounts:profile' user %}">내 프로필</a>
        <form action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="Logout" />
        </form>
        <a href="{% url 'movies:index'%}">Movie</a>
        <a href="{% url 'community:index'%}">Community</a>
        <a href="{% url 'community:create'%}">New Review</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}">Signup</a>
        <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
      </nav>
      {% block content %} 
      {% endblock content %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    {% block script %} 
    {% endblock script %}
    {% comment %} 이거 안 넣어줘서.. 실행 자체가 안 됨.. {% endcomment %}
  </body>
</html>